#!/usr/bin/env python3
"""Build the launcher icon layers and the Play listing icon from one geometry.

The mark is a TV showing a password field mid-entry: three dots and a cursor.
It says what the app does (type on your TV) in a shape that still reads at
48dp, where the old rendered keyboard turned into a purple smudge.

Writes the adaptive icon's background, foreground and monochrome layers as
vector drawables, and renders tools/play_icon_512.png with Pillow from the
same numbers. Run from the repo root: python3 tools/make_icon.py

Coordinates are on the 108dp adaptive canvas. Launchers show the centre 72dp
and guarantee only a 66dp circle, so every corner of the TV sits inside a
radius of 33 from the centre. The splash (drawable/splash_icon.xml) animates
the named groups and its cursor offsets assume the dot pitch below.
"""
from pathlib import Path
from PIL import Image, ImageDraw

RES = Path("app/src/main/res/drawable")
PLAY = Path("tools/play_icon_512.png")

# (x, y, w, h, corner radius)
TV = (27, 31.5, 54, 37, 8)
SCREEN = (32, 36.5, 44, 27, 3.5)
STAND = (44, 72, 20, 4, 2)
CURSOR = (65.7, 42.25, 3.6, 15.5, 1.8)
DOT_R = 3.4
DOT_Y = 50
DOTS = (42.1, 50.6, 59.1)

BG_TOP, BG_BOTTOM = "#7C6BFF", "#4338CA"
SCREEN_TOP, SCREEN_BOTTOM = "#1A1560", "#0D0A38"
WHITE = "#FFFFFF"
CURSOR_COLOR = "#46F0C2"

HEADER = '''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/make_icon.py. Edit the script, not this file. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
'''


def n(v):
    return f"{v:g}"


def rrect(x, y, w, h, r):
    arc = f"A{n(r)},{n(r)} 0 0 1"
    # Straight runs are dropped when the corners meet, as on the cursor pill.
    top = f" H{n(x + w - r)}" if w > 2 * r else ""
    bottom = f" H{n(x + r)}" if w > 2 * r else ""
    right = f" V{n(y + h - r)}" if h > 2 * r else ""
    left = f" V{n(y + r)}" if h > 2 * r else ""
    return (f"M{n(x + r)},{n(y)}{top} {arc} {n(x + w)},{n(y + r)}{right} "
            f"{arc} {n(x + w - r)},{n(y + h)}{bottom} {arc} {n(x)},{n(y + h - r)}{left} "
            f"{arc} {n(x + r)},{n(y)} Z")


def circle(cx, cy, r):
    return f"M{n(cx - r)},{n(cy)} A{n(r)},{n(r)} 0 1 0 {n(cx + r)},{n(cy)} A{n(r)},{n(r)} 0 1 0 {n(cx - r)},{n(cy)} Z"


def solid(path, color, indent="    "):
    return (f'{indent}<path\n{indent}    android:fillColor="{color}"\n'
            f'{indent}    android:pathData="{path}" />\n')


def vertical_gradient(path, top, bottom, y0, y1):
    return f'''    <path android:pathData="{path}">
        <aapt:attr name="android:fillColor">
            <gradient
                android:type="linear"
                android:startX="54"
                android:startY="{n(y0)}"
                android:endX="54"
                android:endY="{n(y1)}"
                android:startColor="{top}"
                android:endColor="{bottom}" />
        </aapt:attr>
    </path>
'''


def background():
    return HEADER + vertical_gradient("M0,0 H108 V108 H0 Z", BG_TOP, BG_BOTTOM, 0, 108) + "</vector>\n"


def foreground():
    body = solid(rrect(*TV), WHITE)
    body += vertical_gradient(rrect(*SCREEN), SCREEN_TOP, SCREEN_BOTTOM,
                              SCREEN[1], SCREEN[1] + SCREEN[3])
    body += solid(rrect(*STAND), WHITE)
    for i, x in enumerate(DOTS, 1):
        body += (f'    <group\n        android:name="dot{i}"\n'
                 f'        android:pivotX="{n(x)}"\n        android:pivotY="{n(DOT_Y)}">\n'
                 + solid(circle(x, DOT_Y, DOT_R), WHITE, "        ") + "    </group>\n")
    body += ('    <group android:name="cursor">\n'
             + solid(rrect(*CURSOR), CURSOR_COLOR, "        ") + "    </group>\n")
    return HEADER + body + "</vector>\n"


def monochrome():
    # The system tints this layer, so the screen has to be a hole rather
    # than a dark fill, or themed icons show a solid block.
    frame = rrect(*TV) + " " + rrect(*SCREEN)
    body = ('    <path\n        android:fillColor="#FFFFFF"\n        android:fillType="evenOdd"\n'
            f'        android:pathData="{frame}" />\n')
    body += solid(rrect(*STAND), WHITE)
    for x in DOTS:
        body += solid(circle(x, DOT_Y, DOT_R), WHITE)
    body += solid(rrect(*CURSOR), WHITE)
    return HEADER + body + "</vector>\n"


def rgb(hex_color):
    return tuple(int(hex_color[i:i + 2], 16) for i in (1, 3, 5))


def gradient_fill(size, top, bottom):
    ramp = Image.linear_gradient("L").resize(size)
    return Image.composite(Image.new("RGB", size, rgb(bottom)), Image.new("RGB", size, rgb(top)), ramp)


def play_icon(px=512, ss=4):
    """Render the launcher's visible 72dp crop as the opaque listing icon, so
    the mark is the same size in the store as on the home screen."""
    full = px * ss
    scale = full / 72
    off = 18

    def box(x, y, w, h):
        return [(x - off) * scale, (y - off) * scale, (x + w - off) * scale, (y + h - off) * scale]

    # Background gradient spans the whole 108dp canvas; take the visible band.
    bg = gradient_fill((full, int(108 * scale)), BG_TOP, BG_BOTTOM)
    im = bg.crop((0, int(off * scale), full, int(off * scale) + full))
    draw = ImageDraw.Draw(im)

    x, y, w, h, r = TV
    draw.rounded_rectangle(box(x, y, w, h), r * scale, fill=WHITE)

    x, y, w, h, r = SCREEN
    b = [round(v) for v in box(x, y, w, h)]
    mask = Image.new("L", (b[2] - b[0], b[3] - b[1]))
    ImageDraw.Draw(mask).rounded_rectangle([0, 0, mask.width - 1, mask.height - 1], r * scale, fill=255)
    im.paste(gradient_fill(mask.size, SCREEN_TOP, SCREEN_BOTTOM), b[:2], mask)

    x, y, w, h, r = STAND
    draw.rounded_rectangle(box(x, y, w, h), r * scale, fill=WHITE)
    for cx in DOTS:
        draw.ellipse(box(cx - DOT_R, DOT_Y - DOT_R, 2 * DOT_R, 2 * DOT_R), fill=WHITE)
    x, y, w, h, r = CURSOR
    draw.rounded_rectangle(box(x, y, w, h), r * scale, fill=CURSOR_COLOR)

    return im.resize((px, px), Image.LANCZOS)


def main():
    for name, xml in (("ic_launcher_background", background()),
                      ("ic_launcher_foreground", foreground()),
                      ("ic_launcher_monochrome", monochrome())):
        (RES / f"{name}.xml").write_text(xml)
        print(f"  {RES / name}.xml")
    # Play Console asks for a 32-bit PNG; the alpha channel is simply opaque.
    play_icon().convert("RGBA").save(PLAY)
    print(f"  {PLAY}")


if __name__ == "__main__":
    main()
